#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Aug 26 16:45:40 2022

@author: aurelienb
"""

from pyimfcs.export import merge_excels

folder = "/home/aurelienb/Documents/Projects/imFCS/results/BA/"
files = [["2022_08_09_NR_-BA.xlsx", "NR_-BA_2608.xlsx"],
         ["2022_08_09_NR_+BA.xlsx",'NR_+BA_2608.xlsx']]

files = [ [folder + l for l in ll] for ll in files]
out_name = folder + "merged_NR_BA_diffusion"
conditions = ['- BA', '+BA']
merge_excels(files,out_name,conditions = conditions, chi_threshold=0.03)